# -*- coding: utf-8 -*-
"""Assignment_week1

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1um2K_Fm9p0ibFeqq3jSyOuTZecUHYequ
"""

#Quiz1

kor = 90
mat = 80
eng = 100
sum = kor + mat + eng
avg = int(sum / 3)

print('kor',kor,'\nmat',mat,'\neng',eng,'\nsum',sum,'\navg',avg)

#Quiz2
print('T'*10,'T'*10,' '*4+'TT',' '*4+'TT',' '*4+'TT',sep='\n')

#Quiz3
num1 = 10
num2 = 20
num3 = 30

print(num1,'+',num2,'=',num3)

#Quiz4
num1 = int(input("첫 번째 정수를 입력해주세요: "))
num2 = int(input("두 번째 정수를 입력해주세요: "))
num3 = int(input("세 번째 정수를 입력해주세요: "))

sum = num1 + num2 + num3
avg = int(sum / 3)

print('sum =',sum,'\navg =',avg)

#Quiz5
yard = float(input("yard? "))

centimeter = round(yard*91.44, 1)

print(yard,'yard = ',centimeter,'cm',sep='')